name: Tag After Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag-main:
    name: Tag After Merge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-tags: true

      - name: Determine Version Number
        run: |
          TAG_NAME="v$(cat VERSION)"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create or Update Tag
        run: |
          TAG_NAME=${{ env.TAG_NAME }}
          git tag -f $TAG_NAME
          git push origin $TAG_NAME --force
